// SPDX-License-Identifier: LGPL-3.0-or-later
//! Generates boot_screen_data.s from the logo PNG and font sheet.
//! The payload is 1bpp tiles compressed as LZ77 inside 4-bit Huffman. The logo tiles are stored
//! column-major, with each byte being one 8-pixel column, which compresses the logo best.
const std = @import("std");
const Io = std.Io;
const zigimg = @import("zigimg");
const olz = @import("optimal_lz.zig");
const huffman4 = @import("huffman4.zig");

const FONT = "assets/gbstudio_default_ascii.png";
const LOGO = "assets/emibios_logo_2bpp.png";

const fs = @import("font_sheet.zig");
const Px = fs.Px;

fn buildLogo(gpa: std.mem.Allocator, logo: Px) !struct { raw: []u8, tw: usize, th: usize, ink_h: usize } {
    var minx: usize = logo.w;
    var miny: usize = logo.h;
    var maxx: usize = 0;
    var maxy: usize = 0;
    var found = false;
    for (0..logo.h) |y| for (0..logo.w) |x| {
        if (!fs.isWhite(logo.p[y * logo.w + x])) {
            found = true;
            minx = @min(minx, x);
            maxx = @max(maxx, x);
            miny = @min(miny, y);
            maxy = @max(maxy, y);
        }
    };
    if (!found) return .{ .raw = &.{}, .tw = 0, .th = 0, .ink_h = 0 };
    const tw = (maxx - minx + 1 + 7) / 8;
    const th = (maxy - miny + 1 + 7) / 8;
    const ink_h = maxy - miny + 1;
    var out: std.ArrayList(u8) = .empty;
    for (0..th) |ty| for (0..tw) |txi| {
        for (0..8) |ry| {
            var acc: u8 = 0;
            for (0..8) |rx| {
                const sx = minx + txi * 8 + rx;
                const sy = miny + ty * 8 + ry;
                const oob = sx > maxx or sy > maxy;
                const bit: u8 = if (oob) 0 else (if (fs.isWhite(logo.p[sy * logo.w + sx])) 0 else 1);
                acc |= bit << @intCast(rx);
            }
            try out.append(gpa, acc);
        }
    };
    var g: usize = 0;
    while (g * 8 < out.items.len) : (g += 1) {
        var col: [8]u8 = undefined;
        for (0..8) |c| {
            var acc: u8 = 0;
            for (0..8) |r| acc |= ((out.items[g * 8 + r] >> @as(u3, @intCast(c))) & 1) << @as(u3, @intCast(r));
            col[c] = acc;
        }
        @memcpy(out.items[g * 8 ..][0..8], &col);
    }
    return .{ .raw = out.items, .tw = tw, .th = th, .ink_h = ink_h };
}

fn buildSource(gpa: std.mem.Allocator, io: Io) ![]u8 {
    const font = try fs.loadPng(gpa, io, FONT);
    const logo_px = try fs.loadPng(gpa, io, LOGO);
    const lg = try buildLogo(gpa, logo_px);
    const at = try fs.buildAtlas(gpa, font);

    const logo_t0: usize = 1;
    const atlas_t0 = logo_t0 + lg.tw * lg.th;
    const last_t = atlas_t0 + at.n;

    var art: std.ArrayList(u8) = .empty;
    try art.appendSlice(gpa, lg.raw);
    try art.appendSlice(gpa, at.raw);
    const blob = try huffman4.encode(gpa, try olz.lz(gpa, art.items));

    var aw = std.Io.Writer.Allocating.init(gpa);
    const p = &aw.writer;
    try p.print("@ Generated by tools/boot_screen/gen_boot_screen.zig\n", .{});
    try p.print(
        ".equ BS_LOGO_TW, {d}\n.equ BS_LOGO_TH, {d}\n.equ BS_LOGO_T0, {d}\n.equ BS_LOGO_RAW, {d}\n",
        .{ lg.tw, lg.th, logo_t0, lg.raw.len },
    );
    try p.print(".equ BS_LOGO_INK, {d}\n", .{lg.ink_h});
    try p.print(
        ".equ BS_ATLAS_T0, {d}\n.equ BS_ATLAS_N, {d}\n.equ BS_ATLAS_RAW, {d}\n",
        .{ atlas_t0, at.n, at.raw.len },
    );
    try p.print(".equ BS_LAST_T, {d}\n", .{last_t});
    try p.print(".equ BS_OFF_LOGO, 0\n.equ BS_OFF_ATLAS, {d}\n", .{lg.raw.len});
    try p.print(".equ BS_ART_RAW, {d}\n.align 2\n", .{art.items.len});
    try p.print("bs_blob:\n", .{});
    var i: usize = 0;
    while (i < blob.len) : (i += 16) {
        try p.print("    .byte ", .{});
        const end = @min(i + 16, blob.len);
        for (blob[i..end], 0..) |byte, j| {
            try p.print("{s}0x{x:0>2}", .{ if (j != 0) "," else "", byte });
        }
        try p.print("\n", .{});
    }
    try p.print(".align 2\n", .{});
    return aw.written();
}

pub fn main(init: std.process.Init) !void {
    const gpa = init.arena.allocator();
    const io = init.io;
    const args = try init.minimal.args.toSlice(gpa);
    const src = try buildSource(gpa, io);
    // args[1] = output directory
    if (args.len >= 2 and !std.mem.eql(u8, args[1], "--stdout")) {
        const path = try std.fs.path.join(gpa, &.{ args[1], "boot_screen_data.s" });
        try Io.Dir.cwd().writeFile(io, .{ .sub_path = path, .data = src });
    } else {
        var ow: Io.File.Writer = .init(.stdout(), io, &.{});
        try ow.interface.writeAll(src);
        try ow.interface.flush();
    }
}
