// SPDX-License-Identifier: LGPL-3.0-or-later
//! Handoff-calibration gate and recalibrator.
const std = @import("std");
const Io = std.Io;

const CAL = "src/calibration.s";
const BIOS = "zig-out/bin/gba_bios.bin";
const CYC_PER_ITER: i64 = 4; // FINAL_BURN_PAD step. FINAL_FINE burns one cycle per nop
const FRAME_CYC: i64 = 228 * 1232; // one GBA frame (228 scanlines x 1232 cyc): the BOOT_FRAME_TRIM step
const MAX_ITERS: u32 = 80;
// Build variants share calibration.s
const VARIANTS = [_]struct { sha: []const u8, flags: []const []const u8 }{
    .{ .sha = "bios.sha256", .flags = &.{} },
    .{ .sha = "bios_no_header_check.sha256", .flags = &.{"-Dno-header-check=true"} },
};

fn run(gpa: std.mem.Allocator, io: Io, argv: []const []const u8) !void {
    const r = try std.process.run(gpa, io, .{ .argv = argv });
    switch (r.term) {
        .exited => |c| if (c == 0) return,
        else => {},
    }
    var ew: Io.File.Writer = .init(.stderr(), io, &.{});
    try ew.interface.print("command failed: {s}\n{s}", .{ argv[0], r.stderr });
    try ew.interface.flush();
    return error.SubprocessFailed;
}

fn runCapture(gpa: std.mem.Allocator, io: Io, argv: []const []const u8) ![]u8 {
    const r = try std.process.run(gpa, io, .{ .argv = argv });
    switch (r.term) {
        .exited => |c| if (c == 0) return r.stdout,
        else => {},
    }
    return error.SubprocessFailed;
}

fn parseCyc(s: []const u8) !u64 {
    const cs = (std.mem.indexOf(u8, s, "cyc=") orelse return error.Parse) + 4;
    var ce = cs;
    while (ce < s.len and s[ce] >= '0' and s[ce] <= '9') ce += 1;
    return std.fmt.parseInt(u64, s[cs..ce], 10);
}

// calibration.s is generated, but parsing the existing values keeps recal incremental.
fn readEqu(text: []const u8, name: []const u8) !i64 {
    var keybuf: [64]u8 = undefined;
    const key = try std.fmt.bufPrint(&keybuf, ".equ {s},", .{name});
    const ki = std.mem.indexOf(u8, text, key) orelse return error.NotFound;
    var ns = ki + key.len;
    while (ns < text.len and (text[ns] == ' ' or text[ns] == '\t')) ns += 1;
    var ne = ns;
    while (ne < text.len and (text[ne] == '-' or (text[ne] >= '0' and text[ne] <= '9'))) ne += 1;
    return std.fmt.parseInt(i64, text[ns..ne], 10);
}

fn sha256Hex(gpa: std.mem.Allocator, io: Io) ![64]u8 {
    const data = try Io.Dir.cwd().readFileAlloc(io, BIOS, gpa, .limited(1 << 20));
    var digest: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(data, &digest, .{});
    return std.fmt.bytesToHex(digest, .lower);
}

// recal owns calibration.s; the build gate detects source changes via bios.sha256, so no source hash here.
fn writeCal(gpa: std.mem.Allocator, io: Io, burn: i64, fine: i64, trim: i64) !void {
    const text = try std.fmt.allocPrint(gpa,
        \\@ SPDX-License-Identifier: LGPL-3.0-or-later
        \\@ Generated by tools/recal/recal.zig
        \\.equ FINAL_BURN_PAD, {d}
        \\.equ FINAL_FINE, {d}
        \\.equ BOOT_FRAME_TRIM, {d}
        \\
    , .{ burn, fine, trim });
    try Io.Dir.cwd().writeFile(io, .{ .sub_path = CAL, .data = text });
}

fn writeSha(gpa: std.mem.Allocator, io: Io, sha: []const u8) !void {
    const hex = try sha256Hex(gpa, io);
    const text = try std.fmt.allocPrint(gpa, "{s}  gba_bios.bin\n", .{hex});
    try Io.Dir.cwd().writeFile(io, .{ .sub_path = sha, .data = text });
}

// The inner build must not recurse into the gate.
fn build(gpa: std.mem.Allocator, io: Io, zig: []const u8, flags: []const []const u8) !void {
    try run(gpa, io, try std.mem.concat(gpa, []const u8, &.{ &.{ zig, "build", "-Dno-recal=true" }, flags }));
}

fn measure(gpa: std.mem.Allocator, io: Io, zig: []const u8, probe: []const u8, rom: []const u8, flags: []const []const u8) !u64 {
    try build(gpa, io, zig, flags);
    return parseCyc(try runCapture(gpa, io, &.{ probe, BIOS, rom }));
}

// Default build path: re-pin only if the built BIOS diverged from the committed hash.
fn gate(gpa: std.mem.Allocator, io: Io, zig: []const u8, sha: []const u8, flags: []const []const u8) !void {
    const got = try sha256Hex(gpa, io);
    const raw: []const u8 = Io.Dir.cwd().readFileAlloc(io, sha, gpa, .limited(4096)) catch "";
    const want = std.mem.trim(u8, raw[0..@min(raw.len, 64)], " \t\r\n");
    if (std.mem.eql(u8, &got, want)) return; // deterministic match -> no GBAHawk, no recal
    try run(gpa, io, try std.mem.concat(gpa, []const u8, &.{ &.{ zig, "build", "recal" }, flags }));
}

fn deep(gpa: std.mem.Allocator, io: Io, zig: []const u8, probe: []const u8, rom: []const u8, target: u64, flags: []const []const u8) !void {
    var ew: Io.File.Writer = .init(.stderr(), io, &.{});
    const w = &ew.interface;

    const cal = try Io.Dir.cwd().readFileAlloc(io, CAL, gpa, .limited(1 << 20));
    var burn = try readEqu(cal, "FINAL_BURN_PAD");
    var fine = try readEqu(cal, "FINAL_FINE");
    var trim = readEqu(cal, "BOOT_FRAME_TRIM") catch 0;

    var iter: u32 = 0;
    while (iter < MAX_ITERS) : (iter += 1) {
        const cyc = try measure(gpa, io, zig, probe, rom, flags);
        if (cyc == target) {
            try writeCal(gpa, io, burn, fine, trim); // converged: the BIOS just built carries these constants
            // Rebuild the requested variant last
            for (VARIANTS) |v| {
                try build(gpa, io, zig, v.flags);
                try writeSha(gpa, io, v.sha);
            }
            try build(gpa, io, zig, flags);
            try w.print("recal: pinned handoff cycles={d} (FINAL_BURN_PAD={d} FINAL_FINE={d} BOOT_FRAME_TRIM={d}, {d} iterations)\n", .{ cyc, burn, fine, trim, iter });
            try w.flush();
            return;
        }
        const delta = @as(i64, @intCast(cyc)) - @as(i64, @intCast(target));
        // The boot screen is VBlank-anchored, so a boot-path change can shift the handoff by whole
        // frames that the (sub-frame) burn cannot absorb. Absorb that coarse offset first by trimming
        // hold frames (a late handoff -> trim more frames), then fine-tune with burn/fine.
        if (delta >= FRAME_CYC / 2 or delta <= -FRAME_CYC / 2) {
            const dframes = @divTrunc(delta + (if (delta > 0) FRAME_CYC / 2 else -FRAME_CYC / 2), FRAME_CYC);
            trim += dframes; // delta>0 (late) -> remove hold frames; BOOT_HOLD shrinks by trim
            try w.print("recal: handoff cycles={d} delta={d}; BOOT_FRAME_TRIM={d} (coarse)\n", .{ cyc, delta, trim });
            try w.flush();
            try writeCal(gpa, io, burn, fine, trim);
            continue;
        }
        // Increasing burn delay increases the handoff cycle.
        // Roll fine cycles into FINAL_BURN_PAD so FINAL_FINE stays in range.
        fine -= delta;
        while (fine < 0) {
            fine += CYC_PER_ITER;
            burn -= 1;
        }
        while (fine >= CYC_PER_ITER) {
            fine -= CYC_PER_ITER;
            burn += 1;
        }
        try w.print("recal: handoff cycles={d} delta={d}; FINAL_BURN_PAD={d} FINAL_FINE={d}\n", .{ cyc, delta, burn, fine });
        try w.flush();
        try writeCal(gpa, io, burn, fine, trim);
    }
    return err(io, "recal: did not converge: handoff cycle is outside the burn range");
}

pub fn main(init: std.process.Init) !void {
    const gpa = init.arena.allocator();
    const io = init.io;
    const args = try init.minimal.args.toSlice(gpa);
    if (args.len < 3) return err(io, "usage: recal <gate|deep> <zig> ...");
    const mode = args[1];
    const zig = args[2];
    if (std.mem.eql(u8, mode, "gate")) {
        if (args.len < 4) return err(io, "usage: recal gate <zig> <sha> [build flags]");
        try gate(gpa, io, zig, args[3], args[4..]);
    } else if (std.mem.eql(u8, mode, "deep")) {
        if (args.len < 6) return err(io, "usage: recal deep <zig> <probe> <rom> <target-cycle> [build flags]");
        const target = std.fmt.parseInt(u64, args[5], 10) catch return err(io, "recal deep: bad target cycle");
        try deep(gpa, io, zig, args[3], args[4], target, args[6..]);
    } else return err(io, "unknown mode (expected gate|deep)");
}

fn err(io: Io, msg: []const u8) error{Usage} {
    var ew: Io.File.Writer = .init(.stderr(), io, &.{});
    ew.interface.print("{s}\n", .{msg}) catch {};
    ew.interface.flush() catch {};
    return error.Usage;
}
